name: "Test"

on:
  push:
  # Triggers the workflow on labeled PRs only.
  pull_request_target:
    types: [labeled]

jobs:
  tests:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.event_name == 'push'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Unlabel 'safe to test'
        uses: actions-ecosystem/action-remove-labels@v1
        if: ${{github.event_name != 'push' }} && runner.os == 'Linux'
        with:
          labels: 'safe to test'

      # Configure prerequisites
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Install npm
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install python components
        run: python -m pip install pipenv poetry

      # Generate mocks
      - name: Generate mocks
        run: go generate ./...

      # Lint
      - name: Lint
        run: go vet ./...

      # Run tests
      - name: Tests
        run: go test ./... -v -race -timeout 30m -cover -coverprofile=covprofile -covermode=atomic
        env:
          JF_URL: ${{ secrets.PLATFORM_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.PLATFORM_ADMIN_TOKEN }}
          JFROG_CLI_LOG_LEVEL: "DEBUG"
      # Generate code coverage
      - name: Send coverage
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=covprofile -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: runner.os == 'Linux'